language: cpp
compiler:
  - gcc
before_install:
  - sudo pip install cpp-coveralls
  - mkdir obj
script:
  # - ./configure --enable-gcov && make && make check
  - make
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'