language: objective-c
compiler:
  - gcc
before_install:
  - brew update
  - brew install pyenv
  - eval "$(pyenv init -)"
  - pyenv install 2.7.6
  - pyenv global 2.7.6
  - pyenv rehash
  - pip install cpp-coveralls
  - pyenv rehash
script:
  # - ./configure --enable-gcov && make && make check
  - make
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'